### ISSUE TITLE
Help With Regex

### ISSUE THREAD

**Issue by TheRexter** [ringosham/TranslateMod#12] opened 2021-02-26 16:16 UTC
I think the chat tags are messing up the translation how can I fix it?
![Screen Shot 2021-02-26 at 9 53 25 AM](https://user-images.githubusercontent.com/77691998/109325604-bcaf7e80-781b-11eb-8f35-f5f730fa4538.png)

**Comment by ringosham** [comment] 2021-02-26 17:34
Duplicate of #9

**Closed by ringosham** 2021-02-26 17:34 UTC
